spring:
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/subway?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: masterpw
  jpa:
    hibernate:
      ddl-auto: create

logging:
  level:
    org.hibernate.type.descriptor.sql: info
