version: '3'
services:
  subway-db:
    image: library/mysql:5.7
    container_name: subway-db
    restart: always
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: subway
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: UTC
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d
