version: '3'
services:
  local-db:
    image: brainbackdoor/data-subway:0.0.1
    container_name: subway-migration
    restart: always
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: masterpw
      MYSQL_DATABASE: subway
      MYSQL_USER: root
      MYSQL_PASSWORD: masterpw
      TZ: Asia/Seoul
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d
